/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2026-01-29 03:54:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class brad69_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/tags/box.tag", Long.valueOf(1769658742033L));
    _jspx_dependants.put("/WEB-INF/tags/test2.tag", Long.valueOf(1769656757785L));
    _jspx_dependants.put("/WEB-INF/tags/test3.tag", Long.valueOf(1769657117319L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1769499825575L));
    _jspx_dependants.put("/WEB-INF/tags/product.tag", Long.valueOf(1769658246202L));
    _jspx_dependants.put("jar:file:/C:/Users/User/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BradWeb/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664424678000L));
    _jspx_dependants.put("/WEB-INF/tags/test1.tag", Long.valueOf(1769656439633L));
    _jspx_dependants.put("/WEB-INF/tags/hello.tag", Long.valueOf(1769657220454L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>Insert title here</title>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<h1>Brad Big Company</h1>\r\n");
      out.write("		<hr />\r\n");
      out.write("		");
      if (_jspx_meth_brad_005ftest1_005f0(_jspx_page_context))
        return;
      out.write("<br />\r\n");
      out.write("		");
      if (_jspx_meth_brad_005ftest2_005f0(_jspx_page_context))
        return;
      out.write("<br />\r\n");
      out.write("		");
      if (_jspx_meth_brad_005ftest3_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_brad_005ftest3_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_brad_005ftest3_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_brad_005fhello_005f0(_jspx_page_context))
        return;
      out.write("<br />\r\n");
      out.write("		Product: ");
      if (_jspx_meth_brad_005fproduct_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		<hr />\r\n");
      out.write("		");
      if (_jspx_meth_brad_005fbox_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_brad_005fbox_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_brad_005ftest1_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  brad:test1
    org.apache.jsp.tag.web.test1_tag _jspx_th_brad_005ftest1_005f0 = new org.apache.jsp.tag.web.test1_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_brad_005ftest1_005f0);
    try {
      _jspx_th_brad_005ftest1_005f0.setJspContext(_jspx_page_context);
      _jspx_th_brad_005ftest1_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_brad_005ftest1_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_brad_005ftest2_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  brad:test2
    org.apache.jsp.tag.web.test2_tag _jspx_th_brad_005ftest2_005f0 = new org.apache.jsp.tag.web.test2_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_brad_005ftest2_005f0);
    try {
      _jspx_th_brad_005ftest2_005f0.setJspContext(_jspx_page_context);
      _jspx_th_brad_005ftest2_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_brad_005ftest2_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_brad_005ftest3_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  brad:test3
    org.apache.jsp.tag.web.test3_tag _jspx_th_brad_005ftest3_005f0 = new org.apache.jsp.tag.web.test3_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_brad_005ftest3_005f0);
    try {
      _jspx_th_brad_005ftest3_005f0.setJspContext(_jspx_page_context);
      _jspx_th_brad_005ftest3_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_brad_005ftest3_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_brad_005ftest3_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  brad:test3
    org.apache.jsp.tag.web.test3_tag _jspx_th_brad_005ftest3_005f1 = new org.apache.jsp.tag.web.test3_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_brad_005ftest3_005f1);
    try {
      _jspx_th_brad_005ftest3_005f1.setJspContext(_jspx_page_context);
      _jspx_th_brad_005ftest3_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_brad_005ftest3_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_brad_005ftest3_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  brad:test3
    org.apache.jsp.tag.web.test3_tag _jspx_th_brad_005ftest3_005f2 = new org.apache.jsp.tag.web.test3_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_brad_005ftest3_005f2);
    try {
      _jspx_th_brad_005ftest3_005f2.setJspContext(_jspx_page_context);
      _jspx_th_brad_005ftest3_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_brad_005ftest3_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_brad_005fhello_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  brad:hello
    org.apache.jsp.tag.web.hello_tag _jspx_th_brad_005fhello_005f0 = new org.apache.jsp.tag.web.hello_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_brad_005fhello_005f0);
    try {
      _jspx_th_brad_005fhello_005f0.setJspContext(_jspx_page_context);
      _jspx_th_brad_005fhello_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_brad_005fhello_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_brad_005fproduct_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  brad:product
    org.apache.jsp.tag.web.product_tag _jspx_th_brad_005fproduct_005f0 = new org.apache.jsp.tag.web.product_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_brad_005fproduct_005f0);
    try {
      _jspx_th_brad_005fproduct_005f0.setJspContext(_jspx_page_context);
      // /brad69.jsp(19,11) name = pname type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_brad_005fproduct_005f0.setPname("iPhone");
      // /brad69.jsp(19,11) name = price type = java.lang.Double reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_brad_005fproduct_005f0.setPrice(java.lang.Double.valueOf("32000.5"));
      _jspx_th_brad_005fproduct_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_brad_005fproduct_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_brad_005fbox_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  brad:box
    org.apache.jsp.tag.web.box_tag _jspx_th_brad_005fbox_005f0 = new org.apache.jsp.tag.web.box_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_brad_005fbox_005f0);
    try {
      _jspx_th_brad_005fbox_005f0.setJspContext(_jspx_page_context);
      _jspx_th_brad_005fbox_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_brad_005fbox_005f0, null));
      _jspx_th_brad_005fbox_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_brad_005fbox_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_brad_005fbox_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  brad:box
    org.apache.jsp.tag.web.box_tag _jspx_th_brad_005fbox_005f1 = new org.apache.jsp.tag.web.box_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_brad_005fbox_005f1);
    try {
      _jspx_th_brad_005fbox_005f1.setJspContext(_jspx_page_context);
      // /brad69.jsp(22,2) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_brad_005fbox_005f1.setTitle("Welcome");
      _jspx_th_brad_005fbox_005f1.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_brad_005fbox_005f1, null));
      _jspx_th_brad_005fbox_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_brad_005fbox_005f1);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("Hello,Brad1");
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("			Hello,Brad2\r\n");
      out.write("		");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
